-- MySQL Script generated by MySQL Workbench
-- Sun Aug 14 19:33:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Veterinadiabd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Veterinadiabd` ;

-- -----------------------------------------------------
-- Schema Veterinadiabd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Veterinadiabd` DEFAULT CHARACTER SET latin1 COLLATE latin1_spanish_ci ;
USE `Veterinadiabd` ;

-- -----------------------------------------------------
-- Table `Veterinadiabd`.`Perro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Veterinadiabd`.`Perro` (
  `idperro` INT NOT NULL,
  `sexoperro` VARCHAR(45) NOT NULL,
  `nombreperro` VARCHAR(45) NOT NULL,
  `fechadenacimientoperro` DATETIME NOT NULL,
  `dueñodni` INT NOT NULL,
  `historialid` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idperro`),
  CONSTRAINT `dueñodni`
    FOREIGN KEY (`dueñodni`)
    REFERENCES `Veterinadiabd`.`Dueño` (`dnidueño`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idPerro_UNIQUE` ON `Veterinadiabd`.`Perro` (`idperro` ASC) VISIBLE;

CREATE UNIQUE INDEX `dueñodni_UNIQUE` ON `Veterinadiabd`.`Perro` (`dueñodni` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Veterinadiabd`.`Dueño`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Veterinadiabd`.`Dueño` (
  `dnidueño` INT NOT NULL,
  `nombredueño` VARCHAR(45) NOT NULL,
  `apellidodueño` VARCHAR(45) NOT NULL,
  `telefonodueño` VARCHAR(45) NOT NULL,
  `direcciondueño` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dnidueño`),
  CONSTRAINT `dnidueño`
    FOREIGN KEY (`dnidueño`)
    REFERENCES `Veterinadiabd`.`Perro` (`idperro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '		';

CREATE UNIQUE INDEX `dnidueño_UNIQUE` ON `Veterinadiabd`.`Dueño` (`dnidueño` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Veterinadiabd`.`Historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Veterinadiabd`.`Historial` (
  `idhistorial` INT NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `perro` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `monto` INT NOT NULL,
  `historial_idperro` INT NOT NULL,
  `historial_dueñodni` INT NOT NULL,
  PRIMARY KEY (`idhistorial`),
  CONSTRAINT `historial_idperro`
    FOREIGN KEY (`historial_idperro`)
    REFERENCES `Veterinadiabd`.`Perro` (`idperro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `historial_dueñodni`
    FOREIGN KEY (`historial_dueñodni`)
    REFERENCES `Veterinadiabd`.`Perro` (`idperro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `historial_idperro_UNIQUE` ON `Veterinadiabd`.`Historial` (`historial_idperro` ASC) INVISIBLE;

CREATE INDEX `historial_dueñodni_idx` ON `Veterinadiabd`.`Historial` (`historial_dueñodni` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `veterinadiabd`.`dueño`
(`dnidueño`,
`nombredueño`,
`apellidodueño`,
`telefonodueño`,
`direcciondueño`)
VALUES
(1,
'Luci',
'Sosa',
'1234',
'Mi casa');


INSERT INTO `veterinadiabd`.`perro`
(`idperro`,
`sexoperro`,
`nombreperro`,
`fechadenacimientoperro`,
`dueñodni`,
`historialid`)
VALUES
(2,
'm',
'perro',
'2022-01-01',
1,
'1');

INSERT INTO `veterinadiabd`.`perro`
(`idperro`,
`sexoperro`,
`nombreperro`,
`fechadenacimientoperro`,
`dueñodni`,
`historialid`)
VALUES
(1,
'm',
'perro',
'2022-01-01',
1,
'1');


SELECT * FROM veterinadiabd.perro;

INSERT INTO `veterinadiabd`.`historial` (`idhistorial`, `fecha`, `perro`, `descripcion`, `monto`, `historial_idperro`, `historial_dueñodni`) VALUES ('2', '2020-01-01', '2', 'listo', '130', '2', '1');

SELECT * FROM veterinadiabd.historial ;

DELETE FROM `veterinadiabd`.`perro`
WHERE idperro = 2;
